### ISSUE TITLE
Bluetooth related crash

### ISSUE THREAD

**Issue by sds100** [sds100/KeyMapper#687]
13:13:13.228  Enable service
13:13:16.462  Accessibility service started
13:13:16.463  Accessibility service: request fingerprint gesture detection
13:13:16.464  Accessibility service: deny fingerprint gesture detection
13:13:16.466  Received event from accessibility service: io.github.sds100.keymapper.util.OnShowKeyboardEvent@133cb75
13:13:16.468  Accessibility service: deny fingerprint gesture detection
13:13:16.997  Received event from accessibility service: Pong(key=ping_service)
13:13:17.914  Received event from accessibility service: Pong(key=ping_service)
13:14:48.799  Enable service
13:14:51.629  Accessibility service started
13:14:51.630  Accessibility service: request fingerprint gesture detection
13:14:51.632  Accessibility service: deny fingerprint gesture detection
13:14:51.636  Accessibility service: deny fingerprint gesture detection
13:14:51.637  Received event from accessibility service: io.github.sds100.keymapper.util.OnShowKeyboardEvent@d374a97
13:14:52.143  Received event from accessibility service: Pong(key=ping_service)
13:14:52.566  Received event from accessibility service: Pong(key=ping_service)
13:15:07.468  Accessibility service started
13:15:07.477  Accessibility service: request fingerprint gesture detection
13:15:07.478  Accessibility service: deny fingerprint gesture detection
13:15:07.493  Received event from accessibility service: io.github.sds100.keymapper.util.OnShowKeyboardEvent@81507db
13:15:07.498  Received event from accessibility service: Pong(key=ping_service)
13:15:07.514  Accessibility service: deny fingerprint gesture detection
13:15:29.683  Enable service
13:15:32.141  Accessibility service started
13:15:32.142  Accessibility service: request fingerprint gesture detection
13:15:32.144  Accessibility service: deny fingerprint gesture detection
13:15:32.148  Accessibility service: deny fingerprint gesture detection
13:15:32.149  Received event from accessibility service: io.github.sds100.keymapper.util.OnShowKeyboardEvent@d374a97
13:15:32.683  Received event from accessibility service: Pong(key=ping_service)
13:22:07.390  Received event from accessibility service: Pong(key=ping_service)
13:22:24.348  Received event from accessibility service: Pong(key=ping_service)
15:52:40.542  Received event from accessibility service: Pong(key=ping_service)
15:53:40.891  Received event from accessibility service: Pong(key=ping_service)
15:59:38.565  Received event from accessibility service: Pong(key=ping_service)
16:25:13.183  java.lang.NullPointerException: device.name must not be null
	at io.github.sds100.keymapper.system.bluetooth.AndroidBluetoothAdapter$onReceiveIntent$1.invokeSuspend(AndroidBluetoothAdapter.kt:65)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

16:25:16.618  java.lang.NullPointerException: device.name must not be null
	at io.github.sds100.keymapper.system.bluetooth.AndroidBluetoothAdapter$onReceiveIntent$1.invokeSuspend(AndroidBluetoothAdapter.kt:65)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by sds100** [comment]
fixed
