### ISSUE TITLE
crash on app start up 

### ISSUE THREAD

**Issue by sds100** [sds100/KeyMapper#706]
**Developer TODO (don't remove)**
- [ ] create new branch. put issue number at start of name if not a very quick fix.
- [ ] write tests. put issue number in comment
- [ ] update documentation
- [ ] squash and merge
- [ ] delete branch

**Discord message link/email recipient**

**Describe the bug**
App crashes on start up. The person is using Android 8.1

```

06-23 01:59:35.837 10789  7687  7687 E AndroidRuntime: FATAL EXCEPTION: main
06-23 01:59:35.837 10789  7687  7687 E AndroidRuntime: Process: io.github.sds100.keymapper.ci, PID: 7687
06-23 01:59:35.837 10789  7687  7687 E AndroidRuntime: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
06-23 01:59:35.837 10789  7687  7687 E AndroidRuntime: 	at java.util.ArrayList.get(ArrayList.java:437)
06-23 01:59:35.837 10789  7687  7687 E AndroidRuntime: 	at com.github.appintro.internal.viewpager.PagerAdapter.getItem(PagerAdapter.kt:13)
06-23 01:59:35.837 10789  7687  7687 E AndroidRuntime: 	at com.github.appintro.AppIntroBase$onPostCreate$1.run(AppIntroBase.kt:458)
06-23 01:59:35.837 10789  7687  7687 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:809)
06-23 01:59:35.837 10789  7687  7687 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
06-23 01:59:35.837 10789  7687  7687 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:166)
06-23 01:59:35.837 10789  7687  7687 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7555)
06-23 01:59:35.837 10789  7687  7687 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-23 01:59:35.837 10789  7687  7687 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:469)
06-23 01:59:35.837 10789  7687  7687 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:963)
```

**Comment by sds100** [comment]
fixed
