### ISSUE TITLE
NPE when disabling accessibility volume stream

### ISSUE THREAD

**Issue by sds100** [sds100/KeyMapper#737]
**Developer TODO (don't remove)**
- [x] create new branch. put issue number at start of name if not a very quick fix.
- [x] write tests. put issue number in comment
- [x] update documentation
- [x] squash and merge
- [x] delete branch

**Discord message link/email recipient**

**Describe the bug**
```
14:59:52.899  java.lang.NullPointerException: Attempt to read from field 'int android.accessibilityservice.AccessibilityServiceInfo.feedbackType' on a null object reference
	at io.github.sds100.keymapper.system.accessibility.MyAccessibilityService.disableAccessibilityVolumeStream(Unknown Source:10)
	at io.github.sds100.keymapper.system.accessibility.AccessibilityServiceController$6.invokeSuspend(Unknown Source:131)
	at io.github.sds100.keymapper.system.accessibility.AccessibilityServiceController$6.invoke(Unknown Source:18)
	at kotlinx.coroutines.flow.t$d$a.invokeSuspend(Unknown Source:63)
	at kotlinx.coroutines.flow.t$d$a.invoke(Unknown Source:14)
	at f3.l$a.invokeSuspend(Unknown Source:276)
	at kotlin.coroutines.jvm.internal.a.resumeWith(Unknown Source:9)
	at c3.z0.run(Unknown Source:130)
	at c3.i1.Q(Unknown Source:13)
	at c3.a1.e(Unknown Source:27)
	at c3.a1.a(Unknown Source:69)
	at c3.m.v(Unknown Source:7)
	at c3.m.t(Unknown Source:24)
	at e3.a$b.a(Unknown Source:4)
	at e3.e.x(Unknown Source:90)
	at e3.c.f(Unknown Source:0)
	at e3.h.L0(Unknown Source:2)
	at e3.h.f(Unknown Source:0)
	at f3.y.emit(Unknown Source:2)
	at kotlinx.coroutines.flow.j.b(Unknown Source:157)
	at kotlinx.coroutines.flow.j$a.invokeSuspend(Unknown Source:11)
	at kotlin.coroutines.jvm.internal.a.resumeWith(Unknown Source:9)
	at c3.z0.run(Unknown Source:130)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:7858)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)

```

**Comment by sds100** [comment]
fixed
