### ISSUE TITLE
NPE in LogFragment

### ISSUE THREAD

**Issue by sds100** [sds100/KeyMapper#738]
**Developer TODO (don't remove)**
- [ ] create new branch. put issue number at start of name if not a very quick fix.
- [ ] write tests. put issue number in comment
- [ ] update documentation
- [ ] squash and merge
- [ ] delete branch

**Discord message link/email recipient**
https://discord.com/channels/717499872219103263/717500546910650488/864288402043961374

**Describe the bug**
UI crash in View and share log when (presumably) getting log messages during screen rotation animation.

01:26:23.346  java.lang.NullPointerException
	at io.github.sds100.keymapper.util.ui.RecyclerViewFragment.getBinding(SourceFile:49)
	at io.github.sds100.keymapper.logging.LogFragment$RecyclerViewController.buildModels(SourceFile:149)
	at io.github.sds100.keymapper.logging.LogFragment$RecyclerViewController.buildModels(SourceFile:118)
	at com.airbnb.epoxy.TypedEpoxyController.buildModels(SourceFile:77)
	at com.airbnb.epoxy.EpoxyController$1.run(SourceFile:281)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:227)
	at android.app.ActivityThread.main(ActivityThread.java:7822)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)

**To Reproduce**

1. Enable extra logging
2. Open the log viewer
3. Repeatedly press your keymapped key to generate log messages
4. Rotate your device while you're generating log events
5. The app will crash to the home screen (however, the accessibility service stays alive)

**Comment by sds100** [comment]
fixed
